version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql